apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: rayleshh/argocd-app
<<<<<<< HEAD
=======
  newTag: 6478717616073233498f436e5eee865454b3898f
- name: rayleshh/argocd-deploy
>>>>>>> 8518cacf49d3aeba61f6028aff08b7cec74feb3c
  newTag: 3824e3ce01af4947d4375c2d8fb22159d12e5c04
