apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: rayleshh/argocd-app
  newTag: 0a73ff4389a199d8b02c61625f8a1fef86ea4768
- name: rayleshh/argocd-deploy
  newTag: 3824e3ce01af4947d4375c2d8fb22159d12e5c04
