apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: rayleshh/argocd-app
  newTag: f7b5d8edf3f0d32b0243429fccbe60a4ce88a8a1
